apiVersion: v1
kind: Deployment
metadata:
  name: api-gateway-deployment
  labels:
    app: api-gateway
spec:
  replicas: 2
  selector:
    matchLabels:
      app: api-gateway
  template:
    metadata:
      labels:
        app: api-gateway
    spec:
      containers:
        - name: api-gateway-container
          image: vragalevgeorge/sharing-economy-microservice-api-gateway:v4
          ports:
            - containerPort: 5000
          env:
            - name: ASPNETCORE_URLS
              value: "http://+:5000"
          readinessProbe:
            httpGet:
              path: /status  # This should be the path to your health check endpoint.
              port: 5000
            initialDelaySeconds: 5
            periodSeconds: 5
          livenessProbe:
            httpGet:
              path: /status  # Again, ensure this path matches your health check.
              port: 5000
            initialDelaySeconds: 5
            periodSeconds: 5
