apiVersion: v1
kind: Deployment
metadata:
  name: inventory-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: inventory-service
  template:
    metadata:
      labels:
        app: inventory-service
    spec:
      containers:
        - name: inventory-service
          image: vragalevgeorge/sharing-economy-microservice-inventory-service:v3
          ports:
            - containerPort: 80
          env:
            - name: ConnectionStrings__DefaultConnection
              value: "Host=inventory-db;Username=postgres;Password=postgres;Port=5433;Database=InventoryAPI;Pooling=true;"
            - name: ASPNETCORE_URLS
              value: "http://+:80"
          readinessProbe:
            httpGet:
              path: /api/inventory/status
              port: 80
            initialDelaySeconds: 5
            periodSeconds: 10
          livenessProbe:
            httpGet:
              path: /api/inventory/status
              port: 80
            initialDelaySeconds: 15
            periodSeconds: 20
