version: '3'

networks:
  dev:
    driver: bridge

services:
  inventoryapi:
    depends_on: 
      - "app_db"
    container_name: "inventory-cotnainer"
    ports:
      - "5217:80"
    build:
      context: ./SharingEconomyMicroservices
      dockerfile: Dockerfile.inventory
    environment:
      - ConnectionStrings__DefaultConnection=User ID=postgres;Password=postgres;Server=app_db;Port=5432;Database=InventoryAPI; IntegratedSecurity=true;Pooling=true;
      - ASPNETCORE_URLS=http://+:80
    networks:
      - dev
  
  app_db:
    image: postgres:latest
    container_name: "app_db"
    environment: 
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=InventoryAPI
    ports:
      - "5433:5432"
    restart: "always"
    volumes:
      - app_data:/var/lib/postgresql/data
    networks: 
      - dev
volumes: 
  app_data:
    

#  apigateway:
#    build: ./APIGateWay
#    ports:
#      - "5000:5000"
#    depends_on:
#      - userapi
