apiVersion: v1
kind: ConfigMap
metadata:
  name: prometheus-config
data:
  prometheus.yml: |
    global:
      scrape_interval: 15s
    scrape_configs:
      - job_name: 'api-gateway'
        static_configs:
          - targets: ['api-gateway-service:5000']
      # Add additional scrape_configs here for other services
