apiVersion: v1
kind: StatefulSet
metadata:
  name: hazelcast
spec:
  serviceName: "hazelcast"
  replicas: 3
  selector:
    matchLabels:
      app: hazelcast
  template:
    metadata:
      labels:
        app: hazelcast
    spec:
      containers:
        - name: hazelcast
          image: hazelcast/hazelcast:latest
          ports:
            - containerPort: 5701