apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: C:\Kompose\kompose.exe --file .\docker-compose.yml convert
    kompose.version: 1.26.0 (40646f47)
  creationTimestamp: null
  labels:
    io.kompose.service: inventory-service
  name: inventory-service
spec:
  ports:
    - name: "5217"
      port: 5217
      targetPort: 80
  selector:
    io.kompose.service: inventory-service
status:
  loadBalancer: {}
