FROM mcr.microsoft.com/dotnet/sdk:7.0 AS build-env
WORKDIR /app

EXPOSE 80
EXPOSE 443

# Copy csproj and restore as distinct layers
COPY ./OrderAPI/OrderAPI.csproj ./OrderAPI/
COPY ./OrderBLL/OrderBLL.csproj ./OrderBLL/
COPY ./OrderDAL/OrderDAL.csproj ./OrderDAL/

RUN dotnet restore ./OrderAPI/OrderAPI.csproj

# Copy everything else and build
COPY ./OrderAPI/ ./OrderAPI/
COPY ./OrderBLL/ ./OrderBLL/
COPY ./OrderDAL/ ./OrderDAL/

# Build and publish
WORKDIR /app/OrderAPI
RUN dotnet publish -c Release -o out

# Build runtime image
FROM mcr.microsoft.com/dotnet/aspnet:7.0
WORKDIR /app
COPY --from=build-env /app/OrderAPI/out .
ENTRYPOINT ["dotnet", "OrderAPI.dll"]